from sqlalchemy import (
    Column,
    Integer,
    DateTime,
    Numeric,
    String,
    Text,
    ForeignKey,
    Index,
    UniqueConstraint,
)
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship

from multiTenantApi.models.Base import Base

# =========================
# Match (Proposed / Confirmed) This class is for tha conditional 
# You can model this as:
# • a “candidate” generated by reconciliation + a “confirmed match”, or
# • a single table with status = proposed|confirmed|rejected
# =========================
class Match(Base):
    __tablename__ = "match"

    STATUS_PROPOSED = "proposed"
    STATUS_CONFIRMED = "confirmed"
    STATUS_REJECTED = "rejected"

    id = Column(Integer, primary_key=True)

    tenant_id = Column(
        Integer,
        ForeignKey("tenant.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    invoice_id = Column(
        Integer,
        ForeignKey("invoice.id", ondelete="CASCADE"),
        nullable=False,
    )

    bank_transaction_id = Column(
        Integer,
        ForeignKey("bank_transaction.id", ondelete="CASCADE"),
        nullable=False,
    )

    score = Column(
        Numeric(5, 4),
        nullable=False,
        doc="Confidence score from 0.0000 to 1.0000",
    )

    status = Column(
        String(20),
        default=STATUS_PROPOSED,
        nullable=False,
    )

    ai_explanation = Column(Text, nullable=True)

    created_at = Column(DateTime, server_default=func.now())

    # relationships
    tenant = relationship("Tenant", back_populates="matches")
    invoice = relationship("Invoice", back_populates="matches")
    bank_transaction = relationship(
        "BankTransaction",
        back_populates="matches",
    )

    __table_args__ = (
        UniqueConstraint(
            "tenant_id",
            "invoice_id",
            "bank_transaction_id",
            name="uq_match_unique",
        ),
        Index("ix_match_tenant_status", "tenant_id", "status"),
        Index(
            "ix_match_invoice_bank",
            "invoice_id",
            "bank_transaction_id",
        ),
    )

    def confirm(self):
        self.status = self.STATUS_CONFIRMED
        self.invoice.status = "matched"  # o constante si la tienes

    def __repr__(self):
        return f"<Match invoice={self.invoice_id} bank_tx={self.bank_transaction_id}>"