"""update relationship Tenant/Invoice/Match/Vendor

Revision ID: 518f34190322
Revises: b018604b83ea
Create Date: 2025-12-30 19:56:52.904932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '518f34190322'
down_revision: Union[str, Sequence[str], None] = 'b018604b83ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
