"""initial schema

Revision ID: 5452fb7c6e60
Revises: 
Create Date: 2025-12-30 19:29:39.603269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5452fb7c6e60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tenant_id'), 'tenant', ['id'], unique=False)
    op.create_table('bank_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_id', name='uq_bank_tx_external')
    )
    op.create_index(op.f('ix_bank_transaction_tenant_id'), 'bank_transaction', ['tenant_id'], unique=False)
    op.create_index('ix_bank_tx_tenant_posted', 'bank_transaction', ['tenant_id', 'posted_at'], unique=False)
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_vendor_name')
    )
    op.create_index(op.f('ix_vendor_tenant_id'), 'vendor', ['tenant_id'], unique=False)
    op.create_index('ix_vendor_tenant_name', 'vendor', ['tenant_id', 'name'], unique=False)
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoice_tenant_number', 'invoice', ['tenant_id', 'invoice_number'], unique=False)
    op.create_index('ix_invoice_tenant_status', 'invoice', ['tenant_id', 'status'], unique=False)
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('bank_transaction_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transaction.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'invoice_id', 'bank_transaction_id', name='uq_match_unique')
    )
    op.create_index('ix_match_invoice_bank', 'match', ['invoice_id', 'bank_transaction_id'], unique=False)
    op.create_index(op.f('ix_match_tenant_id'), 'match', ['tenant_id'], unique=False)
    op.create_index('ix_match_tenant_status', 'match', ['tenant_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_match_tenant_status', table_name='match')
    op.drop_index(op.f('ix_match_tenant_id'), table_name='match')
    op.drop_index('ix_match_invoice_bank', table_name='match')
    op.drop_table('match')
    op.drop_index('ix_invoice_tenant_status', table_name='invoice')
    op.drop_index('ix_invoice_tenant_number', table_name='invoice')
    op.drop_table('invoice')
    op.drop_index('ix_vendor_tenant_name', table_name='vendor')
    op.drop_index(op.f('ix_vendor_tenant_id'), table_name='vendor')
    op.drop_table('vendor')
    op.drop_index('ix_bank_tx_tenant_posted', table_name='bank_transaction')
    op.drop_index(op.f('ix_bank_transaction_tenant_id'), table_name='bank_transaction')
    op.drop_table('bank_transaction')
    op.drop_index(op.f('ix_tenant_id'), table_name='tenant')
    op.drop_table('tenant')
    # ### end Alembic commands ###
